### ISSUE TITLE
Hack Club Bank Climate Directory

### ISSUE THREAD

**Issue by garyhtou** [hackclub/site#834]
```[tasklist]
### Tasks
- [ ] https://github.com/hackclub/site/issues/835
- [ ] https://github.com/hackclub/site/issues/836
- [ ] https://github.com/hackclub/site/issues/837
- [ ] https://github.com/hackclub/site/issues/838
```
