### ISSUE TITLE
Bank Climate Directory: Region pages

### ISSUE THREAD

**Issue by garyhtou** [hackclub/site#837]
```[tasklist]
### Tasks
- [ ] Region page routes
- [ ] Transitions & state between home page and region pages
- [ ] Page (re)generation strategy
- [ ] SEO for region pages
```
